version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - f_node_modules:/app/frontend/node_modules
    tty: true
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - b_node_modules:/app/backend/node_modules
    tty: true
    ports:
      - "3001:3001"

volumes:
  f_node_modules:
  b_node_modules:
