version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - f_node_modules:/app/frontend/node_modules
    tty: true
    ports:
      - "3001:3001"

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - b_node_modules:/app/backend/node_modules
    tty: true
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  db:
    image: mysql:8.0
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake

    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  f_node_modules:
  b_node_modules:
  db_data:
