version: "3.7"

services:
  app:
    image: tmp-friends/victo:latest
    container_name: victo
    volumes:
      - ../../app:/var/www
      - node_modules:/var/www/node_modules
    # 本番環境での環境変数はvercelのGUIから設定する
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
    tty: true
    ports:
      - "3000:3000"

volumes:
  node_modules:
