version: "3.7"

services:
  app:
    image: tmp-friends/victo:latest
    container_name: victo
    volumes:
      - ../../app:/var/www
      - node_modules:/var/www/node_modules
    tty: true
    ports:
      - "3000:3000"

volumes:
  node_modules:
